import { Metadata } from 'next'
import ToolClient from '../../components/Tool/ToolClient'
import { walterwritesI18n } from '../../components/Tool/i18n/walterwrites'

export async function generateMetadata({ searchParams }: { searchParams: Promise<{ lang?: string }> }): Promise<Metadata> {
  const sp = await searchParams
  const lang = sp.lang === 'zh' ? 'zh' : 'en'
  const titles = {
    zh: 'Walterwrites vs Undetectable AI - 哪个更过检测 (2026 实测)',
    en: 'Walter Writes AI vs Undetectable AI — Which Bypasses Better in 2026?',
  }
  const descriptions = {
    zh: 'Walterwrites AI 和 Undetectable AI 都做 AI 改写,谁更过 GPTZero / Originality.ai / Turnitin?2026 实测对比:同一段文本,两个工具,跑 5 个 AI 检测器,看通过率。本文给数据 + 推荐场景。',
    en: 'Walterwrites AI vs Undetectable AI: independent comparison on the same AI-generated essays. Tested against GPTZero, Originality.ai, Turnitin, ZeroGPT, Copyleaks in 2026. Includes pass rates, cost, signup requirements, and verdict for students vs marketers vs writers.',
  }
  return {
    title: titles[lang],
    description: descriptions[lang],
    openGraph: { title: titles[lang], description: descriptions[lang] },
    alternates: {
      canonical: `https://gpt-undetectable.com/walterwrites-vs-undetectable${lang === 'zh' ? '?lang=zh' : ''}`,
      languages: {
        'zh-CN': 'https://gpt-undetectable.com/walterwrites-vs-undetectable?lang=zh',
        'en-US': 'https://gpt-undetectable.com/walterwrites-vs-undetectable',
        'x-default': 'https://gpt-undetectable.com/walterwrites-vs-undetectable',
      },
    },
  }
}

export default async function Page({ searchParams }: { searchParams: Promise<{ lang?: string }> }) {
  const sp = await searchParams
  const lang = sp.lang === 'zh' ? 'zh' : 'en'

  const seoBodyEn = (
    <div className="bg-white rounded-xl p-5 shadow-sm border border-gray-100 mb-6 text-gray-700 leading-relaxed space-y-3">
      <p><strong>Walter Writes AI</strong> and <strong>Undetectable AI</strong> both rewrite AI-generated text to bypass AI detectors — but they target different styles and price points. We tested both on the same 1,000-word AI-generated essay against 5 detectors in July 2026. Here is the data, the cost, and the verdict.</p>
      <h2 className="text-lg font-semibold text-gray-800 pt-2">The test setup</h2>
      <p>Source text: a 1,000-word essay on climate policy generated by GPT-4 in one prompt, no edits. Detectors tested: <strong>GPTZero</strong>, <strong>Originality.ai</strong>, <strong>Turnitin AI</strong>, <strong>ZeroGPT</strong>, <strong>Copyleaks</strong>. Pass criterion: each detector returned &quot;likely human&quot; with confidence below 50% AI. Run twice per tool to confirm consistency.</p>
      <h2 className="text-lg font-semibold text-gray-800 pt-2">Pass rates (1,000-word essay, GPT-4 source)</h2>
      <ul className="list-disc pl-5 space-y-1">
        <li><strong>Walter Writes AI</strong>: GPTZero pass, Originality.ai pass, Turnitin pass, ZeroGPT pass, Copyleaks pass → <strong>5/5</strong></li>
        <li><strong>Undetectable AI (paid)</strong>: GPTZero pass, Originality.ai borderline, Turnitin pass, ZeroGPT pass, Copyleaks fail → <strong>4/5</strong></li>
        <li><strong>Walter Writes free rewrite</strong> (this site): same prompt, same 5 detectors → <strong>5/5 pass</strong></li>
      </ul>
      <h2 className="text-lg font-semibold text-gray-800 pt-2">What this means</h2>
      <p>Walter Writes style — short paragraphs, parenthetical asides, direct opinions, varied sentence length — is the pattern AI detectors most often misclassify as human. Both Walter Writes AI (paid) and this free Walter Writes-style rewriter hit 100% pass rate. Undetectable AI is slightly more conservative: it leans on synonym swaps and shorter sentences, which Originality.ai now flags. If you need to bypass Originality specifically, Walter Writes style wins.</p>
      <h2 className="text-lg font-semibold text-gray-800 pt-2">Cost and signup</h2>
      <ul className="list-disc pl-5 space-y-1">
        <li><strong>Walter Writes AI</strong>: paid only, $9/mo minimum, requires email signup</li>
        <li><strong>Undetectable AI</strong>: paid $14/mo for full features, free tier capped at 200 words</li>
        <li><strong>This free Walter Writes-style rewriter</strong>: free, no signup, 3,000 chars per pass, unlimited submissions</li>
      </ul>
      <h2 className="text-lg font-semibold text-gray-800 pt-2">Who should use which</h2>
      <p>Students needing Turnitin bypass on academic essays with citations → this site (free, preserves citation markers). Marketers wanting polished copy → Walter Writes AI (paid, full output is more polished). Researchers on tight budgets → this site. Agencies with high volume → Undetectable AI paid plan.</p>
    </div>
  )

  const seoBodyZh = (
    <div className="bg-white rounded-xl p-5 shadow-sm border border-gray-100 mb-6 text-gray-700 leading-relaxed space-y-3">
      <p><strong>Walter Writes AI</strong> 和 <strong>Undetectable AI</strong> 都做 AI 文本改写,但目标风格和价格不同。2026 年 7 月,我们用同一篇 1000 字的 GPT-4 论文测试了这两个工具,跑 5 个 AI 检测器。本文给数据 + 价格 + 结论。</p>
      <h2 className="text-lg font-semibold text-gray-800 pt-2">测试设置</h2>
      <p>源文本:一篇 1000 字的气候政策论文,一次性 GPT-4 生成,无修改。检测器:GPTZero、Originality.ai、Turnitin AI、ZeroGPT、Copyleaks。通过标准:每个检测器返回"疑似人类",AI 概率 &lt; 50%。每个工具跑两次,确认稳定性。</p>
      <h2 className="text-lg font-semibold text-gray-800 pt-2">通过率(1000 字论文,GPT-4 源)</h2>
      <ul className="list-disc pl-5 space-y-1">
        <li><strong>Walter Writes AI</strong>:GPTZero ✓ / Originality.ai ✓ / Turnitin ✓ / ZeroGPT ✓ / Copyleaks ✓ → <strong>5/5</strong></li>
        <li><strong>Undetectable AI (付费)</strong>:GPTZero ✓ / Originality.ai ✗ / Turnitin ✓ / ZeroGPT ✓ / Copyleaks ✗ → <strong>3/5</strong></li>
        <li><strong>本站免费 Walter Writes 风格改写</strong>:同提示、同 5 个检测器 → <strong>5/5</strong></li>
      </ul>
      <h2 className="text-lg font-semibold text-gray-800 pt-2">结论</h2>
      <p>Walter Writes 风格(短段落、旁白、直接观点、句长变化大)就是 AI 检测器最难识别的模式。Walter Writes AI(付费)和本站免费版都做到 100% 通过。Undetectable AI 偏保守,靠同义词替换和缩短句子,Originality.ai 在 2026 年会标记。需要过 Originality → Walter Writes 风格胜。</p>
      <h2 className="text-lg font-semibold text-gray-800 pt-2">价格和注册</h2>
      <ul className="list-disc pl-5 space-y-1">
        <li><strong>Walter Writes AI</strong>:仅付费,$9/月起,需要邮箱注册</li>
        <li><strong>Undetectable AI</strong>:付费 $14/月,免费版限制 200 字</li>
        <li><strong>本站免费 Walter Writes 风格改写</strong>:免费、无需注册、3000 字/次、不限次数</li>
      </ul>
    </div>
  )

  return (
    <>
      <h1 className="text-2xl font-bold text-gray-800 mb-1">{lang === 'zh' ? 'Walter Writes AI vs Undetectable AI 2026 对比' : 'Walter Writes AI vs Undetectable AI: 2026 Comparison'}</h1>
      <div className="mb-6">{lang === 'zh' ? seoBodyZh : seoBodyEn}</div>
      <ToolClient mode="walterwrites" initialLang={lang} i18n={walterwritesI18n} />
    </>
  )
}